### ISSUE TITLE
Any chance for unhasha?

### ISSUE THREAD

**Issue by derBingle** [sindresorhus/hasha#10]
Just wondered if there would be any possibility of going the opposite direction as well? I love the simplicity of the hasha api and hate requiring yet another module with an inferior api just to get back to a string.

Thanks @sindresorhus! Just for the record, I actually bookmarked https://github.com/sindresorhus?tab=repositories, so whenever I'm looking for something, I can see if you've tackled it yet! 👍

**Comment by sindresorhus** [comment]
Hashing is a way one-way function. You can't get back the original string. Or am I misunderstanding your request?

**Comment by derBingle** [comment]
No, you're definitely not misunderstanding... you're just educating a programming n00b... 🙄  😔

My goal here was to base64 encode/decode stuff. Sorry for the confusion.

**Comment by roccomuso** [comment]
Technically with base64 you can.
