### ISSUE TITLE
Hash multiple files?

### ISSUE THREAD

**Issue by sudo-suhas** [sindresorhus/hasha#13]
Hey, Can I make a PR to hash multiple files? I could use [`combined-stream`](https://github.com/felixge/node-combined-stream) and reuse `hasha.fromStream` to add this functionality.

**Comment by sindresorhus** [comment]
What's your use-case? I've never needed something like that myself.

**Comment by sudo-suhas** [comment]
In `eslint-loader`, I am trying to hash eslint config files to be able to invalidate the cache on config change - https://github.com/MoOx/eslint-loader/issues/43.

**Comment by okbrown** [comment]
Why not loop over multiple files?

**Comment by sudo-suhas** [comment]
@sindresorhus Shall I make the PR?

**Comment by sindresorhus** [comment]
I'm gonna pass on this. It's not something I would ever need and it can be handled by the user if needed.
