### ISSUE TITLE
Any interest in support for CRC?

### ISSUE THREAD

**Issue by DavidAnson** [sindresorhus/hasha#2]
True, CRC is less unique than MD5 - but it has its uses. If you're interested, I created the following Crypto-module-Hash-class-friendly wrapper a while back and could send a PR to add it: https://github.com/DavidAnson/crc-hash

**Comment by sindresorhus** [comment]
> but it has its uses

Your readme should probably elaborate on that. I have no idea what I would use it for.

-

Not really interested in supporting it here. Though feel free to just copy paste the code in this module to make something similar for CRC ;)

**Comment by DavidAnson** [comment]
If you need it, you know it. :) These days, people are probably most likely to encounter CRC variants when working with file formats like PNG, ZIP, and MP3 which use CRCs for checking data integrity.
