### ISSUE TITLE
Add Salt?

### ISSUE THREAD

**Issue by ralphchristianeclipse** [sindresorhus/hasha#23]
Can you add salt on your hash so it's tasty?

**Comment by sindresorhus** [comment]
I assume you want this for hashing a password, in which case, Hasha is not currently a good choice for that. Node.js already has a good built-in method for this: https://stackoverflow.com/a/17201493/64949 Maybe Hasha could expose a higher level password-specific method for encrypting/decrypting a password.

**Comment by ralphchristianeclipse** [comment]
Thanks
