### ISSUE TITLE
New version (5.1.0) hasha.fromFile makes Electron application crash (unallowed memory allocation for worker threads)

### ISSUE THREAD

**Issue by BHuys** [sindresorhus/hasha#24]
I'm using hasha in an Electron app that doesn't support Node 12 yet (v10.15.3). 
Using hasha 5.0.0 there were no problems but since 5.1.0 my application crashes following an error that doesn't get caught in the fromFile promise. 

The problem (I think) is the use of worker_threads in an environment below Node 12 resulting in an unallowed memory allocation windows error when built. 

Locking my hasha version resolved the issue for me but I'm posting this as I don't know this is expected behaviour.

**Comment by sindresorhus** [comment]
This is most likely a bug in Electron. I would recommend opening an issue over at https://github.com/electron/electron
