### ISSUE TITLE
Image hash length

### ISSUE THREAD

**Issue by CaiProgramming** [sindresorhus/hasha#28]
So your package is the fastest yet. other image hashing takes up to 500ms while yours is 5ms. Though there is something i can't figure out. i need to have my hashes around 64 characters and your hashing doesn't seem to have variable hashing length. is there a way to do this?

**Comment by CaiProgramming** [comment]
i need it similar to this. https://www.npmjs.com/package/node-image-hash. though at your speed

**Comment by sindresorhus** [comment]
Hashes are fixed-length, but you can truncate it yourself by slicing it to the length you want.

https://security.stackexchange.com/questions/34796/truncating-the-output-of-sha256-to-128-bits
