### ISSUE TITLE
hasha.fromFile throws error with message "The V8 platform used by this instance of Node does not support creating Workers" when updated to version 5.2.0

### ISSUE THREAD

**Issue by ruk-na-Ziddi** [sindresorhus/hasha#30]
I am using hasha.Fromfile method for creating and comparing hash of two exe files. Recently I updated hasha to v 5.2.0 and I started getting this error. When I revert back to v 5.0.0 then this error is not there.

**Some more details on machine environment:**
Node version: **12.14.0**
npm version: **6.13.0**
OS: **windows**

However, my node and npm version is been same for quiet long. Is there any change in v 5.2.0 compared to v 5.0.0 which can cause this issue. I could not find any changelog document to verify the same.

**Comment by ruk-na-Ziddi** [comment]
Okay, I have some understanding.

I see that in commits there are changes to run fromFile task inside worker thread after v 5.1.0. My code runs the hasha.fromFile inside a chromium instance created by electron, hence there was no filesystem access for worker thread inside the chromium instance.

Please, Let me know if my understanding is correct.

**Comment by sindresorhus** [comment]
Hasha is a Node.js package. Using it for anything outside that, like Electron or bundling, is fine, but then it's your responsibility to find workarounds for issues.
