### ISSUE TITLE
convert to esm

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/hasha#40]
I know you are converting everything to ESM in your one piece and you have a plan laid out. But i just wish to be pinged when it's done.
Thanks in advance ❤️

**Comment by sindresorhus** [comment]
This is now open for contribution. I don't have time right now to do the work myself.

- Need to replace `proxyquire` with something that works for ESM: https://github.com/sindresorhus/hasha/blob/20f46afaed6f68af4ff63a3b4f2fa72ccab8b368/test.js#L36
- Convert to named exports:
  - `hasha.async` => `hash`
  - `hasha` => `hashSync`
  - `hasha.stream` => `hashStream`
  - `hasha.fromStream` => `hashFromStream`
  - `hasha.fromFile` => `hashFromFile`
  - `hasha.fromFileSync` => `hashFromFileSync`

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-move-my-commonjs-project-to-esm
