### ISSUE TITLE
add support to calculate hash of first or last nkb of the file

### ISSUE THREAD

**Issue by beatfreaker** [sindresorhus/hasha#6]
how about adding support to calculate hash of specific part of the file? 
Something like hash of first or last 64 KB of a file, can be useful when using API like [SubDB](http://thesubdb.com/api/) where they require hash of first and last 64 KB of a file.

**Comment by sindresorhus** [comment]
Can you show an example of the API would look like?

**Comment by beatfreaker** [comment]
How about something like this:
```js
hasha.fromFile('unicorn.png', {algorithm: 'md5', calc: '64'}).then(function (hash) {
});
```
here `calc: 'n'` means first n KB, to get last n KB's hash we can use `calc: -n`

**Comment by sindresorhus** [comment]
I've considered this, but decided not to add it here. I've never needed something like this. You can easily achieve it by using [read-chunk](https://github.com/sindresorhus/read-chunk):

```js
var readChunk = require('read-chunk');
var hasha = require('hasha');

hash(readChunk.sync('unicorn.png', 0, 64));
