### ISSUE TITLE
create-hash instead crypto.createHash

### ISSUE THREAD

**Issue by fanatid** [sindresorhus/hasha#9]
if somebody will use this package with browserify bundle size will be awful
you can use [createHash](https://github.com/crypto-browserify/createHash/) (part of crypto-browserify) for decrease bundle size without speed loss

**Comment by sindresorhus** [comment]
I don't see how this is my responsibility? It should be up to Browserify to replace the code correctly. That's the whole point of Browserify, being able to use node modules in the browser without having to care. Seems like the correct solution would be to improve the Browserify detection/replacement logic.

**Comment by fanatid** [comment]
just for you information:
```
$ cat c.js
module.exports = require('crypto')
$ ./node_modules/.bin/browserify c.js |wc -c
542030
$ vim c.js
...
$ cat c.js
module.exports = require('create-hash')
$ ./node_modules/.bin/browserify c.js |wc -c
162758
```

**Comment by sindresorhus** [comment]
@fanatid I didn't mean you were wrong. Just that you're trying to fix it in the wrong place. This way you'll have to try to convince every single module using `crypto` instead of opening an issue on browserify and getting it resolved there.

**Comment by fanatid** [comment]
@sindresorhus I agree that browserify should do this, but it's looks super hard

**Comment by sindresorhus** [comment]
You won't really know that until it's explored though, so I would still strongly encourage you to open an issue on Browserify to start a discussion about it.

As for an immediate solution. Dead-code elimination comes to mind. Both Webpack 2 and Rollup supports that.
